### PR TITLE
initial setup for mixer_tricopter unit tests

### PR DESCRIPTION
**Pull request by pqueiros**
other unit test are broken thus to execute do:

cd /src/test;make test-mixer_tricopter_unittest

stubs will need rework as we implement test cases,
for now aim is to make compiler happy

### CODE REVIEW

**Comment by lkaino** [comment]
Thanks, awesome! So it compiles now?

**Comment by pqueiros** [comment]
Hi,
mixer_tricopter unit tests compile. The previously broken unit test (broken in betaflight some time ago, and your master picked them with a merge) are still broken.

Resuming, "make test" will fail since some unit test projects fail to compile.
Nevertheless the individual compilation of tricopter mixer unit test works so we can start developing these.
The non triflight related unit tests will have to be fixed in betaflight. But as you mentioned implementation is constantly changing thus I feel unit tests will be kind of always broken :).

**Comment by pqueiros** [comment]
@lkaino Hi there, does it make sense to rebase this pull request with the master?
Code base changed quite a lot and there are a few more dependencies that need to be addressed. It is not clear why this was left hanging here, I can put some time one it if I get some sort of assurance that pull request will not be forgotten again ;)

Implementing unit test means that there will be extra effort on maintaining them. Thus it is perfectly ok to not do them now. I just need some feedback ;).

**Comment by lkaino** [comment]
Well it would be super awesome if we had unit tests. This was not merged because I take the time to resolve the conflicts after the CF rebase.

If we had unit tests I would make sure they are up to date (and anyone else who develops). I have kept unit testing in mind while developing, trying to split code into functions where sensible. More splitting probably needs to be done.

**Comment by pqueiros** [comment]
Alright, I am reading, makes sense to get this up and running again. Stay tuned! ;). by the way is there a chat/irc where you are reachable? eg. clean flight irc?

**Comment by pqueiros** [comment]
@lkaino There you go ;).

**Comment by lkaino** [comment]
Thanks!

**Comment by lkaino** [comment]
And for how to reach me, I think I have you in Google Hangouts.

**Pull request merged**
